### ISSUE TITLE
MAX Uplink and Downlink Payload size mismatch for DR0

### ISSUE THREAD

**Issue by WinXprt** [MicrochipTech/atsamr34_lorawan_rn_parser#3]
Hi @gd91,

When I performed the tests with the max Uplink and Downlink Payload Size I have observed a mismatch in the uplink and downlink payload size for DR0 on SAMR34 Xplained Pro.

Please find the details below.

### End device configuration:
1) Frequency: IND865
2) Transmission Type: Unconfirmed
3) Device Class: Class C
4) Activation Mode: OTAA
5) Data Rate: DR0
6) LoRaWAN Specification of the MLS Stack: LoRaWAN 1.0.4 as per the Migration Guide provided in the MLS 1_0_P_5

Network server: The Things Enterprise Stack (TTES)

Performed the tests with different uplink and downlink payload sizes such as 50, 51, 52 bytes.

#### Uplink Payload Size: 50
* DUT was sending only 43 byte for DR0 which has a maximum payload size of 50 bytes. When payload above 43 is sent I got invalid_buf_length.

#### Downlink Payload Size: 50
* Network server is sending the downlink data with 50 bytes, and the end device is receiving all 50 bytes.

Please find the attachments and logs below.
[Updated_MLS_P5_Logs (1).zip](https://github.com/MicrochipTech/atsamr34_lorawan_rn_parser/files/5493594/Updated_MLS_P5_Logs.1.zip)

As per the MLS stack it will support 43 bytes only. Then it should adhere for both uplink and downlink payload size for DR0 right.

In the [lorawan regional specification 1.0.3 rev A](https://lora-alliance.org/sites/default/files/2018-07/lorawan_regional_parameters_v1.0.3reva_0.pdf) for IND865, it is mentioned as below
![image](https://user-images.githubusercontent.com/32786723/98226901-aafc4f80-1f7c-11eb-8963-8e58a80f7c14.png)

If we see the MACPayload size length(M) mentioned above. For DR0, the mac payload size is 59 bytes and if we exclude FHDR and FPORT (8 bytes) then the FRMPayload is 51 bytes.

### Required Information:
1. Why there is a mismatch between max Uplink and Downlink payload size for DR0?
2. After observing the behaviour I was confused with the actual behaviour as per the LoRaWAN specification. Should we consider the maximum payload as FRM payload (51 bytes alone) or FHDR (7 bytes) + FPort (1 byte) + FRMPayload (43 bytes) which totals 51 bytes. Can you make it clear which is the right behaviour for both uplink & downlink when considered with respect to maximum payload used. 

![image](https://user-images.githubusercontent.com/32786723/98227056-d54e0d00-1f7c-11eb-9903-f0f71f724ae8.png)

![image](https://user-images.githubusercontent.com/32786723/98227337-35dd4a00-1f7d-11eb-9ada-bcdbc61564ff.png)
[samr34_mls_1_0_p_5.txt](https://github.com/MicrochipTech/atsamr34_lorawan_rn_parser/files/5493554/samr34_mls_1_0_p_5.txt)

**Comment by gd91** [comment]
Hello @WinXprt ,
It is a known issue and already identified in lorawan_multiband.h module where it currently encodes the N values instead of M values.

For India, go to lorawan_multiband.h file and replace from line 361 with the following and let me know then i'll made the udpate here.

/*IND Default Parameters Based on DataRate*/
/*rxWindowSize , maxPayloadSize0, maxPayloadSize1,rxWindowOffset,spreadingFactor,bandwidth,modulation*/
#define DR0_PARAMS_IN                 {8,59,0,-33,12,BW_125KHZ,MODULATION_LORA}
#define DR1_PARAMS_IN                 {10,59,0,-50,11,BW_125KHZ,MODULATION_LORA}
#define DR2_PARAMS_IN                 {14,59,0,-58,10,BW_125KHZ,MODULATION_LORA}
#define DR3_PARAMS_IN               {26,123,0,-62,9,BW_125KHZ,MODULATION_LORA}
#define DR4_PARAMS_IN               {49,250,0,-66,8,BW_125KHZ,MODULATION_LORA}
#define DR5_PARAMS_IN               {83,250,0,-68,7,BW_125KHZ,MODULATION_LORA}
#define DR6_PARAMS_IN               {0,0,0,0,0,BW_UNDEFINED,MODULATION_LORA}
#define DR7_PARAMS_IN               {8,250,0,-2,0,BW_UNDEFINED,MODULATION_FSK}

**Comment by WinXprt** [comment]
Hi @gd91,

I have made the changes suggested by you. Still, the issue persists.

**Comment by gd91** [comment]
issue will be fixed on next release of MLS

**Comment by WinXprt** [comment]
What could be the probable timeline for the release?

**Comment by WinXprt** [comment]
Hi @gd91,

What could be the probable timeline for the release? It has been 5 and half months already.
