### ISSUE TITLE
Join AU915

### ISSUE THREAD

**Issue by FedericoAndrades** [MicrochipTech/atsamr34_lorawan_rn_parser#4]
I test this RN_PARSER in SAMR34 Xplained Pro but:

I have this problem.
sys reset<CR><LF>
<GS><SUB><ETB>7G<BEL>NW7WG<BEL>n<ETB>W7W§<SO>þ-7GW×;N]fÞG<BEL>N]f¼W7G×ø<SUB>÷;Êw]ç:n<GS>w¸·;®u]ø<LF>
USER BOARD MLS_SDK_1_0_P_5 Oct 30 2020 17:04:32<CR><LF>
mac reset au915<CR><LF>
ok<CR><LF>
mac set edclass c<CR><LF>
ok<CR><LF>
mac set appkey 01010101010101010101010101010101<CR><LF>
ok<CR><LF>
mac set joineui 0000000000000001<CR><LF>
ok<CR><LF>
mac set subband status 1 on<CR><LF>
ok<CR><LF>
mac join otaa<CR><LF>
ok<CR><LF>
**denied**<CR><LF>
 but, the networkserver send "**JoinAcepted**". 

At least a dozen times this happens, before I accept a "join" but I always have to do a "sys reset" and initialize everything again every time until I get the connection.
on the other hand, in class C, it is not responding "ACK" to uplinks with confirmation.

**Comment by gd91** [comment]
This sample demo code is based on Microchip LoRaWAN Stack v1_0_P_5. The issue reported here need to be verified with LoRaWAN Mote application for SAM R34 available within ASFv3.49 on Microchip Studio. If the issue is confirmed, it can be raised thru official case system: https://microchipsupport.force.com/s/article/How-to-submit-a-case
